### ISSUE TITLE
Empty value for parameter 'issue_number': undefined

### ISSUE THREAD

**Issue by FDiskas** [christianvuerings/add-labels#2]
```
Run christianvuerings/add-labels@v1
  with:
    labels: Ready to merge
  env:
    APPROVED: true
    GITHUB_TOKEN: ***
Add labels: Ready to merge to MY_USER/MY_REPO#undefined
##[error]Empty value for parameter 'issue_number': undefined
```
workflow is runned at pull request review
```
on:
  pull_request_review:
    types: [submitted]
  ...
```
